                                                                                                                                                                                                                                                               
Delivered-To: davidtpate@gmail.com
Received: by 10.194.187.134 with SMTP id fs6csp154248wjc;
        Tue, 11 Mar 2014 06:07:17 -0700 (PDT)
X-Received: by 10.66.175.4 with SMTP id bw4mr47587041pac.56.1394543236260;
        Tue, 11 Mar 2014 06:07:16 -0700 (PDT)
Return-Path: <bounces+848413-7590-davidtpate=gmail.com@sgmail.github.com>
Received: from o1.sgmail.github.com (o1.sgmail.github.com. [192.254.114.176])
        by mx.google.com with SMTP id ha5si20209630pbc.60.2014.03.11.06.07.15
        for <davidtpate@gmail.com>;
        Tue, 11 Mar 2014 06:07:16 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-7590-davidtpate=gmail.com@sgmail.github.com designates 192.254.114.176 as permitted sender) client-ip=192.254.114.176;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of bounces+848413-7590-davidtpate=gmail.com@sgmail.github.com designates 192.254.114.176 as permitted sender) smtp.mail=bounces+848413-7590-davidtpate=gmail.com@sgmail.github.com;
       dkim=pass header.i=@sgmail.github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=sgmail.github.com; 
	h=from:to:subject:mime-version:content-type:content-transfer-encoding; 
	s=smtpapi; bh=Ge8j9G4nxr966RFmUcN0SJoviG4=; b=xvtBJuK7fHzDpms92H
	+RPlryp897LpERwCRRVjqzwkILIs5KjhtyycG2LUMMIKT+5pIJjaYS8HVPefc1yH
	vakZRkQgTVa8uHfWv4mUwH1PRLXPbtw+BXzIaDjqRpyNzEi4/Lf75nlOl3zBECHT
	I/S0h1bVusUepit76W8YQQYD0=
Received: by mf207.sendgrid.net with SMTP id mf207.13464.531F0A8217
        Tue, 11 Mar 2014 13:07:14 +0000 (UTC)
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd-012 (SG) with ESMTP id 144b1410f3c.3567.3cafb4
	for <davidtpate@gmail.com>; Tue, 11 Mar 2014 13:07:14 +0000 (GMT)
Date: Tue, 11 Mar 2014 06:07:14 -0700
From: GitHub <noreply@github.com>
To: David Pate <davidtpate@gmail.com>
Message-ID: <531f0a82bda53_426d3fc7963d12a46736c@github-lowworker7-cp1-prd.iad.github.net.mail>
Subject: GitHub explore today Mar 11
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_531f0a82bc7ab_426d3fc7963d12a46724f";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
X-Auto-Response-Suppress: All
tracking: true
categories: explore,explore-period-daily
X-SG-EID: 7CkovWwNXgPAZ5E285LHLfcOcZDdRmgy+U9rVgN5sananY+T3UrXz6RK6mKz2dHDiJx9Vj+uBLaDPvkUYpa1r1qfzLKuUWapD/0RugqLQ8F36L+5GCB4xNmoAioS8ZMNHOvFldxqk4FszStGo8cWhTC60kM0rHbALKMqGLhbV94=
X-SG-ID: Bc4JW+xVSelhQo5SaiCrmaHirxKbrqGWb3uj2rssPD8lqALlVr++cctjM/jE32ZK

----==_mimepart_531f0a82bc7ab_426d3fc7963d12a46724f
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit



Stars from people you follow today Mar 10 - Mar 11
-------------

1. https://github.com/gabrielecirulli/2048 CSS
A small clone of 1024 (https://play.google.com/store/apps/details?id=com.veewo.a1024)

2. https://github.com/OfficeDev/Office-365-SDK-for-Android Java
Office 365 SDK for Android Preview by Microsoft Open Technologies, Inc.


Trending Repositories today Mar 10 - Mar 11
-------------

1. https://github.com/scoutapp/scout_realtime JavaScript
Realtime server metrics in your browser

2. https://github.com/popcorn-time/popcorn-app CSS
An experiment using the peerflix module of nodejs and connecting a bunch of APIs.

3. https://github.com/gabrielecirulli/2048 CSS
A small clone of 1024 (https://play.google.com/store/apps/details?id=com.veewo.a1024)

4. https://github.com/janpaepke/ScrollMagic JavaScript
The jQuery plugin for magical scroll interactions.

5. https://github.com/papers-we-love/papers-we-love 
Papers from the computer science community to read and discuss.

See all trending repositories https://github.com/trending

Stars from GitHub Staff today Mar 10 - Mar 11
-------------

1. https://github.com/scoutapp/scout_realtime JavaScript
Realtime server metrics in your browser

2. https://github.com/popcorn-time/popcorn-app CSS
An experiment using the peerflix module of nodejs and connecting a bunch of APIs.

3. https://github.com/dherman/web-modules 
Specs for ECMAScript modules on the web

4. https://github.com/peterbe/github-pr-triage JavaScript
A dashboard of Github Pull Requests

5. https://github.com/carlosgaldino/alfred-emoji-workflow Ruby
Alfred 2 workflow for searching emoji codes. :shit:


Unsubscribe from these newsletters. https://github.com/mailers/unsubscribe?token=2223120__eyJzY29wZSI6Ik5ld3NsZXR0ZXJTdWJzY3JpcHRpb246dW5zdWJzY3JpYmUiLCJleHBpcmVzIjoxNDI2MDc5MjM0LCJkYXRhIjp7Im5hbWUiOiJleHBsb3JlIn19--b011e3a7aa6ba60ab09c412ea10ef7a1777dd759

----==_mimepart_531f0a82bc7ab_426d3fc7963d12a46724f
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Explore today on GitHub</title>
    <style>
      div.content a{
        color: #4183C4 !important;
        text-decoration: none;
      }
      div.content a:hover {
        color: #4183C4 !important;
        text-decoration: underline !important;
      }


      @media only screen and (max-device-width: 480px) {
        h1[class="heading"] {
          font-size: 26px !important;
        }
        p[class="subtext"] {
          font-size: 13px !important;
        }

        div[class="content"] {
          width: 460px !important;
        }
        div[class="heading-content"] {
          width: 460px !important;
        }

        td[class="stars-column"] {
          width: 0% !important;
          display: none !important;
        }

      }
    </style>
  </head>
  <body bgcolor="#fafafa" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" style="-webkit-font-smoothing: antialiased;width:100% !important;background:#fafafa;-webkit-text-size-adjust:none;">
    <div style="padding: 10px;">

      <div class="heading-content" style="padding-top: 20px; width: 550px; margin: 0 auto;">
  <table>
    <tr>
      <td style="vertical-align: top; width: 70px;">
        <img src="https://github.global.ssl.fastly.net/images/email/explore/octocat.v2.png" width="60" height="60" />
      </td>
      <td>
        <h1 class="heading" style="margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 36px; letter-spacing: -1px; color: #333; font-weight:normal;">
          <a style="margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 36px; letter-spacing: -1px; color: #333; font-weight:normal;" href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBsjidG1qJaowEHCnoUyY2e0RIyxowcai-2FzP2WvOoAxYO_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0iTi9XrsqaF5OkyZN90lw1yZ3ZaMqd1ijFSS48ABz2PFJJXMEO3-2BXgL56kucrC-2B-2FCSpPhN1zz8doiKStABqU-2BAm5r2IYut8NbVddVZGZYiLgqZIanI-2FiWpNtreTL06Yob-2F-2Bbua0koDJEB52jnd5OGy7xGN2De14-2FihTZKs4AKFsKjeQOdyD-2BXAHbmIicVV-2BsKK-2FQkmK79i05JGWEUHxoFNGA-3D-3D">
            Explore today on GitHub
          </a>
        </h1>
        <p class="subtext" style="margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 16px; font-weight: 300; color: #555;">
          Here's what is happening on GitHub 
          today, <strong style="color:#333">Mar 11</strong>.
        </p>
      </td>
    </tr>
  </table>
</div>


        <div class="content" style="margin: 20px auto !important; width: 550px; border: 1px solid #ddd !important; border-radius: 3px !important; box-shadow: 0 1px 3px rgba(0,0,0,0.05) !important; background: #ffffff !important;">

  <h2 style="font-size:18px; line-height:24px; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; margin-top: 0; margin-bottom: 0; font-weight: normal;">
    <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBsjidG1qJaowEHCnoUyY2e0dYmK0ittbMsBlSCWagH51D40CGU78zBkndLR7nZpHX9nNkufXkOA9u1xvorUBEzwf5yMl-2B10TCUOIXY6g9683i-2FqTtJrZmQ7XyI4sLT2G-2BxMkmmFCuogzZ0KWdXKhAAoESqsS5N4cWIJqZ8dWMqMC_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0i2TNJob2prw0PU-2BRjZ-2FclhpssY-2B4LpLQxi3pjJYyCJmUeuOfEvR3aiUVC8Ld4sJjgXYmTeUPH7OpdXg7TfWhwrjrMFR1EkXltte6nvyIhLrbFaXQ60smNqUnOlLknsEeRz6yBs8yWsy5LGitTtGS-2F6q7xcdFD9pcwIcpD9Ct0e3KFw7tubbgE1GMH4qRhNR7VnYe9L96SQJXt8Ol491hdTw-3D-3D" style="color: #333 !important; background-color: #f3f3f3; padding: 10px 20px; display: block; text-decoration:none;"><img src="https://github.global.ssl.fastly.net/images/email/explore/following.v2.png" width="32" height="32" style="vertical-align: middle; margin-right: 15px; margin-left: 5px;" />Starred by people you follow <strong style="font-weight:bold;">today</strong></a>
  </h2>

  <div style="padding: 20px;">
    <table style="border-collapse: collapse; border-spacing: 0; width: 100%;">
      <tr>
  <td style="width: 50px; vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; ">
    <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBo9Mtmcfp4NGFeCOoVdmNj30Lodtns56IoRkEqVzGynBC0jX57kJk9mgkFeGzJYrWVFEZ9w-2BGz84bM3bJB0nNJYIf0p3xq-2F-2FwGtFRsv3FZXkkOV5YcgjzdGoh2Y-2FmEO134zcXAd0va42-2FQbdqf4B0UEqtOvq54yr-2Fh0QgGSmM0KR_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0iDn1f8H1ycWgC5qZU14sMNLrWnNMtaX6w-2BTuLgY-2B2hAOLukOWGajGWsPQd1OKUHUKzV3q0DZg3UYLqx2Jvl5lTswctedJP8BQk-2BKiVxy2TDCPQLeLGTIyNd-2BNh-2Fgdf7mAxSQMJLOusCecHFeb4pTDugdkBlegvKLoAyW4VxWKDM5WatN6k7mI1873FaJ3b7g704v9FC0iIW8ay-2FOYVonFNw-3D-3D"><img src="https://github.com/gabrielecirulli.png" width="40" height="40" style="border-radius: 3px;"/></a>
  </td>
  <td style="vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; word-break: break-all;">
    <h3 style="font-size: 16px; font-weight: bold; margin-top: 0; margin-bottom: 3px; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
      <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBo9Mtmcfp4NGFeCOoVdmNj1NxK-2FWrXzIxABQYbdzEFOKfmqTGVLtAoZsWBvZANtgzYjzzXVQKbfFYYsHpcctsGsT3dHyjt-2BsmzfEfZKl3qYWUa9humBvjb35F3OKYM0gGiXfxbgNMBg8GYNwJUrckybgVHPHW-2BJebDDSG8-2FEFFYj_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0iKxsH1ar9RlmTMcZSIiw0dKM1QABXfobAVn1-2Bmt22QJ2mR8mukaDmriDzWUjlczvd6qVHU-2FMn6nw5rTODDXIo-2BE5-2FPur3JPvr-2Fjugfn6FO3-2FkxVSE53Z5-2BnbRKwd-2FgG-2FtCxRtGYhK4MB3nh083EK1v25a-2BIqmOaNHtms-2FyLdE9ndNaXypAx9OD3-2BrtoPa3Wou3OeBvfbGshBgKO0dMx5l0Q-3D-3D" style="color: #4183C4 !important; text-decoration:none;">gabrielecirulli/2048</a>
    </h3>
    <p class="extra-stars-column" style="font-style:italic;margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: normal; font-size: 12px; color: #444;">
      <span style="margin-right: 10px;">CSS</span>
    </p>
    <p style="margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 14px; font-weight: normal; color: #333; line-height: 20px; word-break: normal;">A small clone of 1024 (https://play.google.com/store/apps/details?id=com.veewo.a1024)</p>
  </td>
  <td class="stars-column" style="vertical-align: top; text-align: right;border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; " nowrap>
    <span style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: bold; font-size: 16px; margin-left: 10px; color: #333;"><img src="https://github.global.ssl.fastly.net/images/email/explore/star.v2.png" width="16" height="16" style="vertical-align: -2px; margin-right: 3px;" />1</span>
  </td>
</tr>

      <tr>
  <td style="width: 50px; vertical-align: top;  padding-top: 15px;">
    <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBncRJY-2BLX79Sz3lEsd610XjmlfTCoBx8cfAHLKv-2BhvwLy6dvkGeKC6JI3-2Bh10kEEOkF6ryvB8F6cFj8Ue3ZPAY1Wv64uSSI6s5ONZut-2FFWUKzznZDv3IB5Gcq5gMRW-2FttIogF6agHWVAOaoqc-2FjPtE0-3D_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0icot3tj5ORePWsOuMRWKLGyF0O5-2FT36R-2FpfofzUBqkIIVBxVeXOahBEkkdzbXuOvK0W6eUytWePOGbfA-2F6xUuiTf0TOK7kZQm1pGcul8L0kl4iuoMBcRTF82QrwOEC8LIiXQ6cQ0xWiAZJz3Cdj9lNfBYjgXzWZbCO6QLs4KsapWP3OvD8WUa9p-2Fff-2FbRTCrPkbGAj0UJOjJJx96ZxLODbg-3D-3D"><img src="https://github.com/OfficeDev.png" width="40" height="40" style="border-radius: 3px;"/></a>
  </td>
  <td style="vertical-align: top;  padding-top: 15px;word-break: break-all;">
    <h3 style="font-size: 16px; font-weight: bold; margin-top: 0; margin-bottom: 3px; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
      <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBncRJY-2BLX79Sz3lEsd610XgZW67NzKxGVJgBggRt9XVxN1vYqTTwN0X7OBUbb5kkK70OtWiWZRtpOwA78kBpJM5g4-2Fiv2n2pn58A9H8R4Euh9rEsk2w7x7t0by2l4hli2iL5UYSsyA8bUi5Idi-2B8gcegn1XdKd0pK2mZPO4Y2t33CiVtLd9bDGweDus-2FpQdq2A-3D-3D_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0i4GT1mNJFgLwjcBC1RNNuxF-2BKi6mLB1J23U1D8uaXZ0ifuFfGiZk4vhWazWclKUrVrwWb9KADxIVZl-2Fw79-2F16HXoOOwkccTDguA30Ca7hBp-2F9H1uu2qiM0UPuzUgVwGoSFFsJZApxozAuDC7rpijgt2ckN9TPVSjMEuZkIcTIaC1uu48jAzsKf7ExnmEvuPtt3nBAPs8UkDXwFcdDrD2qVw-3D-3D" style="color: #4183C4 !important; text-decoration:none;">OfficeDev/Office-365-SDK-for-Android</a>
    </h3>
    <p class="extra-stars-column" style="font-style:italic;margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: normal; font-size: 12px; color: #444;">
      <span style="margin-right: 10px;">Java</span>
    </p>
    <p style="margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 14px; font-weight: normal; color: #333; line-height: 20px; word-break: normal;">Office 365 SDK for Android Preview by Microsoft Open Technologies, Inc.</p>
  </td>
  <td class="stars-column" style="vertical-align: top; text-align: right; padding-top: 15px;" nowrap>
    <span style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: bold; font-size: 16px; margin-left: 10px; color: #333;"><img src="https://github.global.ssl.fastly.net/images/email/explore/star.v2.png" width="16" height="16" style="vertical-align: -2px; margin-right: 3px;" />1</span>
  </td>
</tr>

    </table>
  </div>
</div>


      <div class="content" style="margin: 20px auto !important; width: 550px; border: 1px solid #ddd !important; border-radius: 3px !important; box-shadow: 0 1px 3px rgba(0,0,0,0.05) !important; background: #ffffff !important;">

  <h2 style="font-size:18px; line-height:24px; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; margin-top: 0; margin-bottom: 0; font-weight: normal;">
    <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBhLwountNTN3xU-2FQq5jpFdS716E83nbXJZh0FMYDzHtlD6t0GABEswI2K3Ei8R5262p-2FSXyZ-2F7581cSr5eiiGZhnnI1B6Gh3lEUcj5OCIbDkmgzBKEnimcsU-2FO0s74hneTyv46tOrbcgkknKBXitzmc-3D_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0izoorlYDhr5J7cOHNrkr1ATZ0i5-2FE5-2BDIE7rt4DdbH2ouv-2BFh3gXnoSGXi9pXWPyIO7wYNa6cc1dO08JI-2BFiop-2Fc8mWQ6AU4QbxG5fCbjIYq7ftibiUAKXP1MLNfvDU4QykmpLGpJks9ZDyRzyB3Qn4N3Mf-2BUk4xOEyzy8dnfDTskJjJf5zSijGjzdMW331FG-2FMhjYRJNC0YhzqHbM49jCg-3D-3D" style="color: #333 !important; background-color: #f3f3f3; padding: 10px 20px; display: block; text-decoration:none;"><img src="https://github.global.ssl.fastly.net/images/email/explore/pulse.v3.png" width="32" height="32" style="vertical-align: middle; margin-right: 15px; margin-left: 5px;" />Trending repositories <strong style="font-weight:bold;">today</strong></a>
  </h2>

  <div style="padding: 20px;">
    <table style="border-collapse: collapse; border-spacing: 0; width: 100%;">
    <tr>
  <td style="width: 50px; vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; ">
    <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBuf4U00rBqQjYV77TFmkCgPHUOgqdNMAXH5QetLAJtVyrTM8PE6-2FEHFHHqR2YuW7cNhRZ0Yg4Q4dVwpoNyN0kG9b-2F1moXVJ72rJpVO-2FzoOCncu2AeC7mfIyEwn1ST0SgZvVJYThmcHGeK2f9XP2U7kE-3D_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0idYFJT-2Fqt8qtU848OuLf5bFudtvWgQRV-2FMJ-2BxuwpQgy8Srh8IH6u-2BbVNGcnniRQvKhSSimNy1yKrD13zp6WHmPHjMfMztOXQTOy95A7LIx4woIjQsdUF61VV8D4LO3-2FTm2oZRE3DTl0hBw1rKY4bGKJajeJhE49G2ofof6PaeHMSnWyuNVzIWpPvBldBTPWcKZmx4Qeg103rOowUzIvvhNA-3D-3D"><img src="https://github.com/scoutapp.png" width="40" height="40" style="border-radius: 3px;"/></a>
  </td>
  <td style="vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; word-break: break-all;">
    <h3 style="font-size: 16px; font-weight: bold; margin-top: 0; margin-bottom: 3px; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
      <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBuf4U00rBqQjYV77TFmkCgPF4dZl-2Fb0xTy6t4eWtXKho9SlDB-2BhqEWQ2opvarOTZAX733GxC-2BMBCqK-2BRi6UzxqZ86GyhbxEvjnyzR9RECGCA3dUFb-2Bop-2FmHzmNBG6Q1NIuJmqhgDy1sfDxjjGf8P06wKsOGUOuhaw-2FMbyLDqPZAo_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0isHiDOa3-2F-2FAx-2Fn36DVHFVDLrS2ozXpSxpvDC9F0igNHecgnzo80w6jbJh-2FSK5M55-2FnFfLLQC7HCrs-2F022lYQYrKZxeZLgkD5MB7XHdhwWjuIHOpBgB-2F-2FVgJO6yILL5FQCmR8HhfKfG-2Fkkn8orYTq4D3kk30E-2BKJSwcMnIui3O1RWKXD1EiSX-2FwFFDWZfYH5HnaX-2FkoJPfhtJmlq4vb5eSDg-3D-3D" style="color: #4183C4 !important; text-decoration:none;">scoutapp/scout_realtime</a>
    </h3>
    <p class="extra-stars-column" style="font-style:italic;margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: normal; font-size: 12px; color: #444;">
      <span style="margin-right: 10px;">JavaScript</span>
    </p>
    <p style="margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 14px; font-weight: normal; color: #333; line-height: 20px; word-break: normal;">Realtime server metrics in your browser</p>
  </td>
  <td class="stars-column" style="vertical-align: top; text-align: right;border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; " nowrap>
    <span style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: bold; font-size: 16px; margin-left: 10px; color: #333;"><img src="https://github.global.ssl.fastly.net/images/email/explore/star.v2.png" width="16" height="16" style="vertical-align: -2px; margin-right: 3px;" />509</span>
  </td>
</tr>

    <tr>
  <td style="width: 50px; vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;">
    <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBgyKsLnkSqxjLCulIBh8ysZF1N-2B3eVVO8-2BeFmWJuVeg1BJgjSZIE-2BaD-2F03-2F4h8sTczOBfiPM4CgiP2Ts3I7M-2F7qqL9S6t0U9un0g-2Bf1xgP6qknaeastDIru6kAYgGkbNcTHB0mCiTVj2gpSy6MG-2Bfqg-3D_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0i8UwVCXFEN2gCGg-2FXYzpBPediPXOvOYDgmdYV7-2FdpXQG1Kh-2FJb-2FtesBvMsd49Vuim-2FqNGlsrb4-2FfZOiVmWbzoMpPYaqQB9xe8-2Be2hlvKyLXSric7U5DRLbM5EUDQfWeOBkYNNddO-2BUnkku-2F33M6tHjq76ek244c7bdkuzcC8tDkqDMMpDO9z7hzIoGcs7tsoj0WSXFIJopHGTvdCGPZjVEA-3D-3D"><img src="https://github.com/popcorn-time.png" width="40" height="40" style="border-radius: 3px;"/></a>
  </td>
  <td style="vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;word-break: break-all;">
    <h3 style="font-size: 16px; font-weight: bold; margin-top: 0; margin-bottom: 3px; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
      <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBgyKsLnkSqxjLCulIBh8ysYREv28NStFwB-2BiUMgcErArQn5wkntmc8kI23bDMHYXTmqhfr5nlsr57LIw7dbdfxtfdFss-2FS3GjNzTW17fmnPz2mf97Z-2F7kBHPeWqfRw7c-2BE1ehIo2hz2t2HW37iCJIV-2BAT8uOvYV8-2FT0CP4ZwFck6_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0igPzyMKzue8DixU62R6b-2F9lDz-2FQmSGeNTHtBn4bsgtMoXY4Bo-2Bl4sdMTabjwWe90eFwMSt5xpJ8sfLfX5xsIInYPqcKjySzboLXUGxJkMiRZ3cfWNHa9ugwsCykwuoHXVPwF51fdlgAa18LfBy-2FAQo3FoRbL9IS-2FTdNTB1DPQgUFljXoL2ubLCFT1q4iclatjA0YjKQTH45jssvNpGdXP-2Fg-3D-3D" style="color: #4183C4 !important; text-decoration:none;">popcorn-time/popcorn-app</a>
    </h3>
    <p class="extra-stars-column" style="font-style:italic;margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: normal; font-size: 12px; color: #444;">
      <span style="margin-right: 10px;">CSS</span>
    </p>
    <p style="margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 14px; font-weight: normal; color: #333; line-height: 20px; word-break: normal;">An experiment using the peerflix module of nodejs and connecting a bunch of APIs.</p>
  </td>
  <td class="stars-column" style="vertical-align: top; text-align: right;border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;" nowrap>
    <span style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: bold; font-size: 16px; margin-left: 10px; color: #333;"><img src="https://github.global.ssl.fastly.net/images/email/explore/star.v2.png" width="16" height="16" style="vertical-align: -2px; margin-right: 3px;" />398</span>
  </td>
</tr>

    <tr>
  <td style="width: 50px; vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;">
    <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBo9Mtmcfp4NGFeCOoVdmNj30Lodtns56IoRkEqVzGynBC0jX57kJk9mgkFeGzJYrWVFEZ9w-2BGz84bM3bJB0nNJYIf0p3xq-2F-2FwGtFRsv3FZXkkOV5YcgjzdGoh2Y-2FmEO134zcXAd0va42-2FQbdqf4B0UEqtOvq54yr-2Fh0QgGSmM0KR_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0i98e7O8er-2Bq-2F7jycyvtlHV7xrBC3VTW5NcSgfJ0al9Z0TBT49MH-2FxKBDCN5nilbvzwazBNj39T5Rxz-2B2emcYuhplmQ7-2F-2BrwU3Sfj9QIaCKcA9aKbctyxGflx8N-2FaxrRaJ0hFB6s-2FRgVh409l1B9Mb4DsO2jvNanwXQd7eHFbP5KyA91LkNZx-2Fd-2ByOm3M77cVp5O3fH2SNmTDOofXx7lDYpA-3D-3D"><img src="https://github.com/gabrielecirulli.png" width="40" height="40" style="border-radius: 3px;"/></a>
  </td>
  <td style="vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;word-break: break-all;">
    <h3 style="font-size: 16px; font-weight: bold; margin-top: 0; margin-bottom: 3px; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
      <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBo9Mtmcfp4NGFeCOoVdmNj1NxK-2FWrXzIxABQYbdzEFOKfmqTGVLtAoZsWBvZANtgzYjzzXVQKbfFYYsHpcctsGsT3dHyjt-2BsmzfEfZKl3qYWUa9humBvjb35F3OKYM0gGiXfxbgNMBg8GYNwJUrckybgVHPHW-2BJebDDSG8-2FEFFYj_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0iMRme5Ll2XaFgUy7rUWnrXQ0S8hyXF7cXS8mwzHnYoH8r6Ovh1UmevJzLU-2BOaxD8exfAwsuEM-2B6q68LFZs5VA-2BGc8IpAlR7W5AUefgS4iIbhZK5BJaAslKe-2BW6ez-2FZqUD83yOdQA8ShjgKWvNgWI3GP7XcqKyRYN3E5XuzGAIMs9khm-2FfbgWccmdutBZkzOdEb5l4hi0r-2Fz4haimVUGbW-2FQ-3D-3D" style="color: #4183C4 !important; text-decoration:none;">gabrielecirulli/2048</a>
    </h3>
    <p class="extra-stars-column" style="font-style:italic;margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: normal; font-size: 12px; color: #444;">
      <span style="margin-right: 10px;">CSS</span>
    </p>
    <p style="margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 14px; font-weight: normal; color: #333; line-height: 20px; word-break: normal;">A small clone of 1024 (https://play.google.com/store/apps/details?id=com.veewo.a1024)</p>
  </td>
  <td class="stars-column" style="vertical-align: top; text-align: right;border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;" nowrap>
    <span style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: bold; font-size: 16px; margin-left: 10px; color: #333;"><img src="https://github.global.ssl.fastly.net/images/email/explore/star.v2.png" width="16" height="16" style="vertical-align: -2px; margin-right: 3px;" />391</span>
  </td>
</tr>

    <tr>
  <td style="width: 50px; vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;">
    <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBmvJNMYEA2tenis-2FgK5CMeDx3Ur8QEfB0WJaYZSkfncjaykTyPWVTyFN1g-2BS5-2FM8aPqUmAde8RyjC6MaraX5-2B39fEAIEaCaJ7f1A5xTE-2FRjktYARe5ZO0IKkkgNX2Ztm9ROwnAnLy4JpthTFABB7tw0-3D_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0iJnNJRSDsNEPGlj4-2FsM6k2ZaRGb1WtBQQ5k2BPEcj7-2FdJcLD9jRVIp7LQ-2BDm2RMycH55dTiTr7KLL5AVhbOJPKpTa5PbL3NbC9NI49frNlw57MgsPYAJT5YZUTA6MMDCpsPme4Sq-2FWCQspL15CI4iBp244C3ESc4rD6TIYSug-2BRGe6NXHTGMWfdxgUKtFzDg8E1saRd2ZijQfPsL1o9eaxw-3D-3D"><img src="https://github.com/janpaepke.png" width="40" height="40" style="border-radius: 3px;"/></a>
  </td>
  <td style="vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;word-break: break-all;">
    <h3 style="font-size: 16px; font-weight: bold; margin-top: 0; margin-bottom: 3px; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
      <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBmvJNMYEA2tenis-2FgK5CMeAKitF3WywvDvM2i9s-2Fxnya-2FkF4IsHbx18efQG5YslkSRm3ASM4myF9oN4gJlqNfrcu-2Fbm-2F7nduLzojay9kr-2FWAE8bG6h9k0UCha5jnrOqgRnMw91Sn1aYtSuj-2BIrcFdMV6396W-2Fgtr-2FLJ6KXxTgZeH_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0irDL1TOgvq7hRoldiN6weBS3Tc6Fl7YBkBcAC5VzV4DF7bOte0ROQh9YKI9ZN7J7SXEgGgdI9Yd4CyiGiRFB9sFlkGFcFVMfmvVh8tUIou4HRwmAsexTfn0dDhwODOE7CnQYwyueUKGxLpcDvLWGXhsT-2FV16OMNWvnAffrpLEi0I2S4TZIYF2yjADJnXPmDv1KIRQgMjU5mZNSWJtE6sUvA-3D-3D" style="color: #4183C4 !important; text-decoration:none;">janpaepke/ScrollMagic</a>
    </h3>
    <p class="extra-stars-column" style="font-style:italic;margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: normal; font-size: 12px; color: #444;">
      <span style="margin-right: 10px;">JavaScript</span>
    </p>
    <p style="margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 14px; font-weight: normal; color: #333; line-height: 20px; word-break: normal;">The jQuery plugin for magical scroll interactions.</p>
  </td>
  <td class="stars-column" style="vertical-align: top; text-align: right;border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;" nowrap>
    <span style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: bold; font-size: 16px; margin-left: 10px; color: #333;"><img src="https://github.global.ssl.fastly.net/images/email/explore/star.v2.png" width="16" height="16" style="vertical-align: -2px; margin-right: 3px;" />385</span>
  </td>
</tr>

    <tr>
  <td style="width: 50px; vertical-align: top;  padding-top: 15px;">
    <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBrR9lOyRNVFbrQX23Wr5qGGEL5ai6fDLJIZhX-2BWKFBxIj-2F306oSigJHKPgtaXY-2FfAWtpBjBW18mcbVU3GuPiBzilOkospTqvD5BIoNxh3eNCLChIOu7n6zodiTewa1ND84mQjTUNhJAZpeEgm-2BUKgNgSXydQ9KbPYj-2FjYz0Db7jZ_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0iEpsgfdj-2Bgf-2FhqmUAfyJ0-2BuPMEEiJZBH-2Fjv26QxmQwD9Pd9MfELBCmW89tYFs-2BUPqrQUZSd4YdO2l4mj6gMGDPTXDxeQMri0vWvyRI-2Baa7M7X2QLCKS1EToB9pf4Q9Ca9I-2BLuPrLYQhJbSeoZiV2k2TDCSAJg3K6Mt2GmBmmm6UFwoylpgEhExHxqFKOEavW4WIqE6xZHq7lppO9xrquoDg-3D-3D"><img src="https://github.com/papers-we-love.png" width="40" height="40" style="border-radius: 3px;"/></a>
  </td>
  <td style="vertical-align: top;  padding-top: 15px;word-break: break-all;">
    <h3 style="font-size: 16px; font-weight: bold; margin-top: 0; margin-bottom: 3px; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
      <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBrR9lOyRNVFbrQX23Wr5qGGPnC3rsZBobDOBUarlVt-2BlagYupw0ixJVfsGWPYthqcWvQolz-2Fg1mVUKL5qSRX-2FvZZPWl-2F9PoDGxzkGzsXA-2F8vKK59OYGaWWkdGaaPAnz3hRxabUsuJOGRSOdkZPjOgiBUpNEBwOZi5o-2FjaON7QQWU_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0iQ17eJeaSipONiY5KCX5OyxtAgGfta49uHJRQh3lkA9-2B954F2B7N9TMI2IMbxIT-2FCvx9jJ2dafKCLs7J4plaQRQV4XOmUKrE21o-2B-2Bgqw80d7-2FSzZOY-2FNCioGOS4S3WkYTa8fF8lDK0icQNCZDJwtBP5a9xelemiQD01eoFoM7MkcK4gveT6O8En2tWOO8CNXs-2F3JjibOGZamSS-2B5yKBo68w-3D-3D" style="color: #4183C4 !important; text-decoration:none;">papers-we-love/papers-we-love</a>
    </h3>
    <p class="extra-stars-column" style="font-style:italic;margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: normal; font-size: 12px; color: #444;">
      
    </p>
    <p style="margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 14px; font-weight: normal; color: #333; line-height: 20px; word-break: normal;">Papers from the computer science community to read and discuss.</p>
  </td>
  <td class="stars-column" style="vertical-align: top; text-align: right; padding-top: 15px;" nowrap>
    <span style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: bold; font-size: 16px; margin-left: 10px; color: #333;"><img src="https://github.global.ssl.fastly.net/images/email/explore/star.v2.png" width="16" height="16" style="vertical-align: -2px; margin-right: 3px;" />292</span>
  </td>
</tr>

    </table>
  </div>

</div>


        <div class="content" style="margin: 20px auto !important; width: 550px; border: 1px solid #ddd !important; border-radius: 3px !important; box-shadow: 0 1px 3px rgba(0,0,0,0.05) !important; background: #ffffff !important;">

  <h2 style="font-size:18px; line-height:24px; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; margin-top: 0; margin-bottom: 0; font-weight: normal;">
    <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBsjidG1qJaowEHCnoUyY2e0dYmK0ittbMsBlSCWagH51D40CGU78zBkndLR7nZpHX9nNkufXkOA9u1xvorUBEzwf5yMl-2B10TCUOIXY6g9683i-2FqTtJrZmQ7XyI4sLT2G-2BxMkmmFCuogzZ0KWdXKhAAo9bFa7lYZF0I3lpejwTAes_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0iRSSVHQE4MT0DNmHp8IlDcRG0-2B4ELuUrDu0I36clbhYNh2W5ipbEFa3TqhMY05vJJx-2BXmuEvfq-2BacHfwbVpuMVt0YWWr-2BCLN9y5YfkBEoGhWzGxpR-2Bz2errstAl1g9hgN8-2BPyVGC667xft0i-2FO9MGY-2F4qCfykYWyDc1lfVnB-2FlX72g29-2BpmWiXM5rjAQMEtONri-2F7vponlSaFHGhFgqvNHA-3D-3D" style="color: #333 !important; background-color: #f3f3f3; padding: 10px 20px; display: block; text-decoration:none;"><img src="https://github.global.ssl.fastly.net/images/email/explore/octocat.v2.png" width="32" height="32" style="vertical-align: middle; margin-right: 15px; margin-left: 5px;" />Starred by GitHub staff <strong style="font-weight:bold;">today</strong></a>
  </h2>

  <div style="padding: 20px;">
    <table style="border-collapse: collapse; border-spacing: 0; width: 100%;">
    <tr>
  <td style="width: 50px; vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; ">
    <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBuf4U00rBqQjYV77TFmkCgPHUOgqdNMAXH5QetLAJtVyrTM8PE6-2FEHFHHqR2YuW7cNhRZ0Yg4Q4dVwpoNyN0kG9b-2F1moXVJ72rJpVO-2FzoOCncu2AeC7mfIyEwn1ST0SgZvVJYThmcHGeK2f9XP2U7kE-3D_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0i35iDRdhdjpDiZX1Npdmo7CAwWEFFKW4mj0Llsd03SrxHgvdndet3b7xGStQQOKCijS5Q-2FuGKf30GuGJafB6tEAuL-2FWfwhFTJ5689MWgkKe83Xm35pAYTFYBOGiy1KCh-2Bqc6gV-2BNpvQHGYZha1zpHz5vm9-2F3di7oGZqo67Sk-2FzLJ-2BPLtIn-2FD-2FKTF8h8K1de20xI8CFgSLQG-2FQh44UK77cyQ-3D-3D"><img src="https://github.com/scoutapp.png" width="40" height="40" style="border-radius: 3px;"/></a>
  </td>
  <td style="vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; word-break: break-all;">
    <h3 style="font-size: 16px; font-weight: bold; margin-top: 0; margin-bottom: 3px; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
      <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBuf4U00rBqQjYV77TFmkCgPF4dZl-2Fb0xTy6t4eWtXKho9SlDB-2BhqEWQ2opvarOTZAX733GxC-2BMBCqK-2BRi6UzxqZ86GyhbxEvjnyzR9RECGCA3dUFb-2Bop-2FmHzmNBG6Q1NIuJmqhgDy1sfDxjjGf8P06wKsOGUOuhaw-2FMbyLDqPZAo_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0ipF-2FO8eseEN1V2E0KaSEc1rJdsgsoyNICC-2Fe9BEF6LvQFzPifAahcdOWnEX6RIF48w6ulzR-2F-2BZ68j6oMD5fv-2BbEUC-2B3q2bs3Co5H4IKtmVB3n-2F6EFVBLcyde-2BpMSnU4IWej9Ubl-2FFqllmAUymI38QF6n3g2dMsVKh9bw39d06tPt7HMH2FBfN-2B4mqXCui0PDaVkeLYXI6CRgdgn33VrPHMQ-3D-3D" style="color: #4183C4 !important; text-decoration:none;">scoutapp/scout_realtime</a>
    </h3>
    <p class="extra-stars-column" style="font-style:italic;margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: normal; font-size: 12px; color: #444;">
      <span style="margin-right: 10px;">JavaScript</span>
    </p>
    <p style="margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 14px; font-weight: normal; color: #333; line-height: 20px; word-break: normal;">Realtime server metrics in your browser</p>
  </td>
  <td class="stars-column" style="vertical-align: top; text-align: right;border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; " nowrap>
    <span style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: bold; font-size: 16px; margin-left: 10px; color: #333;"><img src="https://github.global.ssl.fastly.net/images/email/explore/star.v2.png" width="16" height="16" style="vertical-align: -2px; margin-right: 3px;" />2</span>
  </td>
</tr>

    <tr>
  <td style="width: 50px; vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;">
    <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBgyKsLnkSqxjLCulIBh8ysZF1N-2B3eVVO8-2BeFmWJuVeg1BJgjSZIE-2BaD-2F03-2F4h8sTczOBfiPM4CgiP2Ts3I7M-2F7qqL9S6t0U9un0g-2Bf1xgP6qknaeastDIru6kAYgGkbNcTHB0mCiTVj2gpSy6MG-2Bfqg-3D_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0iceIt1h3jnIY5sPayV6x0MDGFNEcQHoXn-2FBNyNlq36zYwyo7dPbRMNeLJj86Lp43SS70Kn0st6egx5jX13o2fdw6TWVJix7T6-2FnhNKcAyQZVr6jv2m-2FYmzRw8RhGeReHaFr-2F4eZh7K7fROCzoKbwCyYRG-2FxVQXKyn1GjnUQsPamyz39n-2F4NXldIEa4KTliIJVNRPnbCfP0Xgyi73f18LL2Q-3D-3D"><img src="https://github.com/popcorn-time.png" width="40" height="40" style="border-radius: 3px;"/></a>
  </td>
  <td style="vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;word-break: break-all;">
    <h3 style="font-size: 16px; font-weight: bold; margin-top: 0; margin-bottom: 3px; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
      <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBgyKsLnkSqxjLCulIBh8ysYREv28NStFwB-2BiUMgcErArQn5wkntmc8kI23bDMHYXTmqhfr5nlsr57LIw7dbdfxtfdFss-2FS3GjNzTW17fmnPz2mf97Z-2F7kBHPeWqfRw7c-2BE1ehIo2hz2t2HW37iCJIV-2BAT8uOvYV8-2FT0CP4ZwFck6_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0i6CBn8QBDg0qESwuG92QfIIM4bPTNzIsNYELrVJT7CPhjXWXwQRDQk3rFIM3tEL6Txvl4ioTIKTcne6XX5kqKN7UPPmoKyYfsbNn-2FaBu8h5X-2BDdYDLjappyc7-2BTM6SqBI5wLypQQ37cLEOuUrpCKL2d5NH42ifxaisl45pgoPiuvPbcCwMWjZG8-2BdoTIwsdpgCJJ05WEq1ORJBRXsqNk6LA-3D-3D" style="color: #4183C4 !important; text-decoration:none;">popcorn-time/popcorn-app</a>
    </h3>
    <p class="extra-stars-column" style="font-style:italic;margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: normal; font-size: 12px; color: #444;">
      <span style="margin-right: 10px;">CSS</span>
    </p>
    <p style="margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 14px; font-weight: normal; color: #333; line-height: 20px; word-break: normal;">An experiment using the peerflix module of nodejs and connecting a bunch of APIs.</p>
  </td>
  <td class="stars-column" style="vertical-align: top; text-align: right;border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;" nowrap>
    <span style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: bold; font-size: 16px; margin-left: 10px; color: #333;"><img src="https://github.global.ssl.fastly.net/images/email/explore/star.v2.png" width="16" height="16" style="vertical-align: -2px; margin-right: 3px;" />2</span>
  </td>
</tr>

    <tr>
  <td style="width: 50px; vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;">
    <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBiCh7OUPkv6MKKW0zNVOZpbRIc87GZzFRLQDjdyR8ZNPmqxWv2-2FyvhAgzncT-2Bk73D-2BMYTUVYNDccguVWKwjU6cXWq-2B1UubzyxRX0adhhD4RQpCqzaialF4Dsn14GeTdVosRZs9rF1G41utbVASvuHeY-3D_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0ijYq9UIboggImWKHkUi1rr8eFrJscj6Z2RpK38G-2FPe4KweOgHBiQ0j7wwO5UPrUwkp-2ByDD6MSnj3lqblKphh7jnV0CcawEaNK1mZMNEyBDs9D7fghKVegy3z-2BNFA0-2BXRaNMWCxde9-2FemNcij4asLfu3TzGBXL4cfB-2F5WFU8IFFW2DJwU5OUqinZyIgZetc4XD1QnNOgU5A4bVWKbDro-2B1Nw-3D-3D"><img src="https://github.com/dherman.png" width="40" height="40" style="border-radius: 3px;"/></a>
  </td>
  <td style="vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;word-break: break-all;">
    <h3 style="font-size: 16px; font-weight: bold; margin-top: 0; margin-bottom: 3px; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
      <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBiCh7OUPkv6MKKW0zNVOZpalaj4-2BoN6x3gqNxFLQVW-2Fm08q6-2BBOBi9KRfZLH9BYa1n9T3yT03CclYg-2BdXEKB-2FYGG95K-2FkJG5RtLVXr7R90WKlZs1b-2FyXwkxoQNm2Oy61DjevDlx4g8Qsagjo7PxnSEv0wkEVHH7I52ASyP-2BRh3ar_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0iqDAQpXlFzIm0FBOeR-2Br4IM5Qcmii7GyO1d4psbOMxD-2B4cGAO4jtm3X6Hijq8i3QWhez1v0Fy5aB6TiLTnHsgiHCJyQ8CTA0TB5YhGAksL014pViiuGvRZzHFm97fwz0AqbXtxFcyoskR49V84bAp7wsImHg8-2FKsgUvKwR66mQ6USBXpuiPHcsQPF-2FlYPWddC9v-2B5I7VQ7OHpMkASJ5Y4ZA-3D-3D" style="color: #4183C4 !important; text-decoration:none;">dherman/web-modules</a>
    </h3>
    <p class="extra-stars-column" style="font-style:italic;margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: normal; font-size: 12px; color: #444;">
      
    </p>
    <p style="margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 14px; font-weight: normal; color: #333; line-height: 20px; word-break: normal;">Specs for ECMAScript modules on the web</p>
  </td>
  <td class="stars-column" style="vertical-align: top; text-align: right;border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;" nowrap>
    <span style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: bold; font-size: 16px; margin-left: 10px; color: #333;"><img src="https://github.global.ssl.fastly.net/images/email/explore/star.v2.png" width="16" height="16" style="vertical-align: -2px; margin-right: 3px;" />1</span>
  </td>
</tr>

    <tr>
  <td style="width: 50px; vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;">
    <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBg5lJE9svpcIbbq6-2BT7-2BOLnpAldmyugQgaq7Iw4u2Yd4zVYvng7Gt8wx-2FaMqt1omLK2MfHG8cIENtRtck5lZmW1ZoDp92EYV5r37cxcGOlPBR2fIPwEp0GWBil92H6LF3sOqpp2sYBMiAgC-2BBTtq1Gc-3D_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0i-2FJgRaG8Oe663IL0vICmR1KsBOevFoxX3VCXWESZFKb01QMx2S-2F4eL1VufGD6IJ-2FZAWtkT6RChA4NWBsTYc2WIOz4szZGiIiTkn9ycUC-2FKKgUGAahYJpsGfgBew8tNNtuEwJ9UldVbTVPMDi0Yuw8C2DJQBJIAnLzKB6c4yrqefsZVhrETjH-2BMzzv1CRmo6hfGFATc1baoStQe8GLw334Ow-3D-3D"><img src="https://github.com/peterbe.png" width="40" height="40" style="border-radius: 3px;"/></a>
  </td>
  <td style="vertical-align: top; border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;word-break: break-all;">
    <h3 style="font-size: 16px; font-weight: bold; margin-top: 0; margin-bottom: 3px; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
      <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBg5lJE9svpcIbbq6-2BT7-2BOLlPMLqzf2uPyGlrXabsUHKnvL82eXB4J4CzoFFQwiMWOw84upQvGxWXPNBv9P0rwmQA1f-2FS8A2e7do9lnR-2Bat3wIm9lxvbbgopH1xsBaZyStyyGey7eGrhdd5rRhaPnHDKyv3hhlSJo2sp0zTYjB-2Flt_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0iUhPvavBSQjXtg-2FWJa6BtQGRcRBcZEarhvqa7rikK2FEqE7z6fe7kuc4P6gMIOM-2F-2BERsmSb8cJZ-2FgNWvcPqvu087woR4AopkA5ZLCUs4vfvzGj8ctpVMilzYtuOKzvJRvzIu9pdWNqpc1bRwaw7QZOp32O0lwwJHW-2BojWGHlp4LFBxI4bL-2B0TOFG9MSEYwBpWnUDLA8XSHP3CnXvWkMZ6Gg-3D-3D" style="color: #4183C4 !important; text-decoration:none;">peterbe/github-pr-triage</a>
    </h3>
    <p class="extra-stars-column" style="font-style:italic;margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: normal; font-size: 12px; color: #444;">
      <span style="margin-right: 10px;">JavaScript</span>
    </p>
    <p style="margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 14px; font-weight: normal; color: #333; line-height: 20px; word-break: normal;">A dashboard of Github Pull Requests</p>
  </td>
  <td class="stars-column" style="vertical-align: top; text-align: right;border-bottom: 1px solid #e9e9e9; padding-bottom: 15px; padding-top: 15px;" nowrap>
    <span style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: bold; font-size: 16px; margin-left: 10px; color: #333;"><img src="https://github.global.ssl.fastly.net/images/email/explore/star.v2.png" width="16" height="16" style="vertical-align: -2px; margin-right: 3px;" />1</span>
  </td>
</tr>

    <tr>
  <td style="width: 50px; vertical-align: top;  padding-top: 15px;">
    <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBh5hRP8gz79imMO4a-2FxU2Bbippy8Gn5u72HSG-2BV3-2Fi4q-2F24j6NZSuMLTudcKgGlToyj8bSvpvc2rllM7hUPxNdsrqt5IHHTQ8MWjhskv-2B9VAtKoF3TK5VSmS7kJokKxlHnlA5svhP7tPAEQYRGS99nU-3D_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0ihu9Gx9g-2BJ2NoAQoiY4JNqiWyC4o-2B1V7yf4f-2BpOxyrS8HLqkjH1XwvGa-2BqGRVoP-2BBoC9dqgPuxZf2e1uNiBAWGO8Se9HYEUQVX9Q8nPKVhMb09XReRvkXKVLpVOcrlYEPATE5Rssv5Npvo6rA3fsoWCp43VsLCpWoM37lU6OWHpwUj8ucXXG2WsU-2BTFjqOezUbJp4P0u-2FOYifFHBOn5T-2BRw-3D-3D"><img src="https://github.com/carlosgaldino.png" width="40" height="40" style="border-radius: 3px;"/></a>
  </td>
  <td style="vertical-align: top;  padding-top: 15px;word-break: break-all;">
    <h3 style="font-size: 16px; font-weight: bold; margin-top: 0; margin-bottom: 3px; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
      <a href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBh5hRP8gz79imMO4a-2FxU2BYdZ7wKz4phCxMuPqYG-2B1pw1B5HeKH5EIT7RqY-2F9TjbFWvYMMD1T0728K-2BluScJFmyvgaU7OmOXQr0Wh5g5i13svMM5mu1ix0OlUsYwqgFQBX87fBgcJAM3j9ys7kcMFxK8u4vSTf9o9-2BNlzKJFHo9kOOyBASn-2BPl-2BlJCQwEFv91A-3D-3D_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0iv-2BGEjzQYD2-2F7D4IuioxL5U-2BFV5zVat6TB5WkZDAId38p7P1mlfspFvr-2FuSFdExI5mz6OTjlMykcSSrxQPTrUeuU4PE3EUCO9eSF8-2Fxp2BHKSy1pk0FYK18aIbF0qCqo9Wkeq1vgxKuM08jIPUgSVEqCSFn2HNP6EoK32d-2FBSlKC-2FRFsdkUhUSba-2BpkC3wwq-2FxtTFEknI4v7CooPAX75arw-3D-3D" style="color: #4183C4 !important; text-decoration:none;">carlosgaldino/alfred-emoji-workflow</a>
    </h3>
    <p class="extra-stars-column" style="font-style:italic;margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: normal; font-size: 12px; color: #444;">
      <span style="margin-right: 10px;">Ruby</span>
    </p>
    <p style="margin: 0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 14px; font-weight: normal; color: #333; line-height: 20px; word-break: normal;">Alfred 2 workflow for searching emoji codes. :shit:</p>
  </td>
  <td class="stars-column" style="vertical-align: top; text-align: right; padding-top: 15px;" nowrap>
    <span style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: bold; font-size: 16px; margin-left: 10px; color: #333;"><img src="https://github.global.ssl.fastly.net/images/email/explore/star.v2.png" width="16" height="16" style="vertical-align: -2px; margin-right: 3px;" />1</span>
  </td>
</tr>

    </table>
  </div>

</div>


      <div class="content" style="font-size: 12px; color: #222; margin: 10px auto !important; width: 540px;"><a style="color: #222; font-weight: normal; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; text-decoration: none;" href="http://sgmail.github.com/wf/click?upn=lYxq-2FYU7yocrdKNILYalBiTxQx8FzJStCf8QIl5rIeq2OIXQPQDsdDZjcvLpC8LtLccE7kFBGMsDYYPIGIjwEcuvfMvw6ZdU7w2EqGLl4iBBXxwG65wM-2FxbsEXvqQzMCps5-2FBV5EElv1VLp7pn9InN-2FHSu-2F5wT3FS0Bq1aKt0xluMBXkC-2Bjk79wBKsabg4BItGGbKKjX4PI9xdhWUZVX-2Ba8UL0RVi94T07b6JMoNdj21-2F7EXycABPyAUjCRM81xdSIZQU3-2BhLVgl1a0uuKJ3yBBDKpPgZvVir8he8-2FrdfZZdwntn85BKGl9QMOQrZVCM_IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0i5SOHgKIlBAQ7lLF1WufhyUWnh-2FUv21o2CPcYwfZ4dPfcNIncbDwYRyM4BUOt-2BkpM3uMUyLWmfdyQgXWQCJEa1nmvcLneOD67v0aGbF34y2lbBjwNAKM8HKmdalCBEIMoI91oW0rE9klS9jjCbGTMMA0yumRFxyCpVnzrH1hKtuu8LmZNCvhRw19koPRND87SSnnEKX8dqfdTdzlttjMtvA-3D-3D">Unsubscribe from these newsletters.</a></div>

      <div class="mark" style="margin: 20px 0; text-align: center;">
        <img src="https://github.global.ssl.fastly.net/images/email/explore/octocat.v2.png" width="40" height="40" />
      </div>
    </div>
  
<img src="http://sgmail.github.com/wf/open?upn=IA6XOnfVkDJHmEgCxylrwqxUAvh9JYbVL6M1-2B-2FmA5phTfRudCh9Qy00WuhwVJS0iBlg3deojrswdwm0-2FnhoD1I6zmovVjdRV8rR8SO8UTHo3w4oC7J5cG5Anqbfpv2z-2BWxQCVWTXcEWZvblldIVRCRULb6BuL7l92d-2BAZpbvFkot1lLlwq-2FzNCMM4YdabIpoibLYU9I8v9hU774-2BiQEqUmKOa89Txt1KvhJkzCIjJC-2B173k5S4BYqXIzn4zlqG0QOV7PrZ9-2BYkKcyNPEz40-2BnA-3D-3D" alt="" width="1" height="1" border="0" style="height:1px !important;width:1px !important;border-width:0 !important;margin-top:0 !important;margin-bottom:0 !important;margin-right:0 !important;margin-left:0 !important;padding-top:0 !important;padding-bottom:0 !important;padding-right:0 !important;padding-left:0 !important;"/>
</body>
</html>


----==_mimepart_531f0a82bc7ab_426d3fc7963d12a46724f--